FutureCode1603/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('lib/', include('library.urls')),
    path('shop/', include('shop.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

FutureCode1605/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('lib/', include('library.urls')),
    path('shop/', include('shop.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from .views import *
from .views import *
from django.urls import path, include
urlpatterns = [
    path('product/all/', list_product, name='product_list'),
    path('product/all-filter/', product_list_with_filter, name='product_list_filter'),
    path('product/one-filter/', get_one_filter, name='product_one_filter'),
    path('product/more-filter/', get_more_filter, name='product_more_filter'),
    path('product/detail/<int:id>/', get_one_product, name='get_one_product'),
]

shop/models.py
from django.db import models
from django.urls import reverse_lazy

# Create your models here.
MAX_LENGTH_CHAR = 255

class Supplier(models.Model):
    name = models.CharField(max_length=MAX_LENGTH_CHAR, unique=True, verbose_name='Название компании')
    agent_lastname = models.CharField(max_length=MAX_LENGTH_CHAR, verbose_name='Фамилия представителя')
    agent_name = models.CharField(max_length=MAX_LENGTH_CHAR, verbose_name='Имя представителя')
    agent_surname = models.CharField(max_length=MAX_LENGTH_CHAR, null=True, blank=True, verbose_name='Отчество представителя')
    agent_telephone = models.CharField(max_length=16, verbose_name='Телефон представителя')
    address = models.CharField(max_length=MAX_LENGTH_CHAR,verbose_name='Адрес')
    is_exists = models.BooleanField(default=True, verbose_name='Логическое удаление')

    def __str__(self):
        return self.name
    class Meta:
        verbose_name = 'Поставщик'
        verbose_name_plural = 'Поставщики'

class Supply(models.Model):
    date_supply = models.DateTimeField(verbose_name='Дата поставки')
    supplier = models.ForeignKey(Supplier, on_delete=models.PROTECT, verbose_name='Поставщик')

    product = models.ManyToManyField('Product', through='Pos_supply', verbose_name='Товар')

    def __str__(self):
        return f'{self.pk} - {self.date_supply}'

    class Meta:
        verbose_name = 'Поставка'
        verbose_name_plural = 'Поставки'


class Parametr(models.Model):
    name = models.CharField(max_length=MAX_LENGTH_CHAR, unique=True, verbose_name='Название')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Характеристика'
        verbose_name_plural = 'Характеристики'

class Tag(models.Model):
    name = models.CharField(max_length=MAX_LENGTH_CHAR, unique=True, verbose_name='Название')
    description = models.CharField(max_length=MAX_LENGTH_CHAR, blank=True, null=True, verbose_name='Описание')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Тег'
        verbose_name_plural = 'Теги'

class Category(models.Model):
    name = models.CharField(max_length=MAX_LENGTH_CHAR, unique=True, verbose_name='Название')
    description = models.CharField(max_length=MAX_LENGTH_CHAR, verbose_name='Описание')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'


class Order(models.Model):
    SHOP = "SH"
    COURIER = "CR"
    PICKUPPOINT = "PP"
    TYPE_DELIVERY = [
        (SHOP, 'Магазин'),
        (COURIER, 'Доставка курьером'),
        (PICKUPPOINT, 'Пункт выдачи')

    ]
    buyer_lastname = models.CharField(max_length=MAX_LENGTH_CHAR, verbose_name='Фамилия покупателя')
    buyer_name = models.CharField(max_length=MAX_LENGTH_CHAR, verbose_name='Имя покупателя')
    buyer_surname = models.CharField(max_length=MAX_LENGTH_CHAR, blank=True, null=True, verbose_name='Отчество покупателя')
    comment = models.CharField(max_length=MAX_LENGTH_CHAR, blank=True, null=True, verbose_name='Комментарий к заказу')
    delivery_address = models.CharField(max_length=MAX_LENGTH_CHAR, blank=True, null=True, verbose_name='Адрес доставки')
    delivery_type = models.CharField(max_length=2, choices=TYPE_DELIVERY, default=SHOP, verbose_name='Способ доставки')
    date_create = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    date_finish = models.DateTimeField(null=True, blank=True, verbose_name='Дата завершения')

    product = models.ManyToManyField('Product', through='Pos_order', verbose_name='Товар')

    def __str__(self):
        return f'{self.pk} - ({self.buyer_lastname} {self.buyer_name}) {self.date_create}'


    class Meta:
        verbose_name = 'Заказ'
        verbose_name_plural = 'Заказы'


class Product(models.Model):
    name = models.CharField(max_length=MAX_LENGTH_CHAR, unique=True, verbose_name='Название')
    description = models.CharField(max_length=MAX_LENGTH_CHAR, blank=True, null=True, verbose_name='Описание')
    price = models.FloatField(verbose_name='Цена')
    create_date = models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')
    update_date = models.DateTimeField(auto_now=True, verbose_name='Дата последнего изменения')
    photo = models.ImageField(upload_to='image/%Y/%m/%d', null=True, blank=True, verbose_name='Фотография товара')
    is_exists = models.BooleanField(default=True, verbose_name='Логическое удаление')

    warehouse = models.ManyToManyField('Warehouse', through='Inventory', verbose_name='Склад')
    parametr = models.ManyToManyField(Parametr, through='Pos_parametr', verbose_name='Характеристики товара')
    category = models.ForeignKey(Category,on_delete=models.PROTECT, verbose_name='Категория')
    tag = models.ManyToManyField(Tag, blank=True, verbose_name='Тег')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Товар'
        verbose_name_plural = 'Товары'



class Pos_parametr(models.Model):
    product = models.ForeignKey(Product, on_delete=models.PROTECT, verbose_name='Товар')
    parametr = models.ForeignKey(Parametr, on_delete=models.PROTECT, verbose_name='Характеристика')
    value = models.CharField(max_length=MAX_LENGTH_CHAR, verbose_name='Значение')

    def __str__(self):
        return f'{self.product.name} - {self.value}'

    class Meta:
        verbose_name = 'Характеристика товара'
        verbose_name_plural = 'Характеристики товаров'

class Pos_order(models.Model):
    product = models.ForeignKey(Product, on_delete=models.PROTECT, verbose_name='Товар')
    order = models.ForeignKey(Order, on_delete=models.PROTECT, verbose_name='Заказ')
    count = models.PositiveIntegerField(default=1, verbose_name='Количество товара')
    discount = models.PositiveIntegerField(default=0, verbose_name='Скидка')

    def __str__(self):
        return f'{self.order.pk} {self.product.name} - {self.order.buyer_lastname}'

    class Meta:
        verbose_name = 'Позиция заказа'
        verbose_name_plural = 'Позиции заказов'


class Pos_supply(models.Model):
    product = models.ForeignKey(Product, on_delete=models.PROTECT, verbose_name='Товар')
    supply = models.ForeignKey(Supply, on_delete=models.PROTECT, verbose_name='Поставка')
    count = models.PositiveIntegerField(verbose_name='Количество товара')

    def __str__(self):
        return f'{self.product.name} - #{self.supply.pk}'

    class Meta:
        verbose_name = 'Позиция поставки'
        verbose_name_plural = 'Позиции поставок'


class Warehouse(models.Model):
    AIRPLANE = "AR"
    TRAIN = "TR"
    TRUCK = "TC"
    ALL = "AL"
    TYPE_POST = [
        (AIRPLANE, 'Отправка самолетом'),
        (TRAIN, 'Отправка поездом'),
        (TRUCK, 'Отправка грузовиком'),
        (ALL, 'Любой вид отправки'),
    ]
    owner_lastname = models.CharField(max_length=MAX_LENGTH_CHAR, verbose_name='Фамилия владельца')
    owner_name = models.CharField(max_length=MAX_LENGTH_CHAR, verbose_name='Имя владельца')
    owner_surname = models.CharField(max_length=MAX_LENGTH_CHAR, blank=True, null=True, name='Отчество владельца')
    location = models.CharField(max_length=MAX_LENGTH_CHAR, verbose_name='Расположение')
    type_post = models.CharField(max_length=2, choices=TYPE_POST, default=ALL, verbose_name='Способ отправки')
    capacity = models.PositiveIntegerField(default=10000, verbose_name='Вместимость')

    def __str__(self):
        return f'{self.location} ({self.capacity} ячеек)'

    class Meta:
        verbose_name = 'Склад'
        verbose_name_plural = 'Склады'


class Inventory(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name='Товар')
    warehouse = models.ForeignKey(Warehouse, on_delete=models.CASCADE, verbose_name='Склад')
    quantity = models.PositiveIntegerField(verbose_name='Количество')
    single_position = models.FloatField(verbose_name='Вес одной позиции')

    def __str__(self):
        return f'{self.product.name} хранится в #{self.warehouse.pk} ({self.quantity})'

    class Meta:
        verbose_name = 'Хранение позиции'
        verbose_name_plural = 'Хранение позиций'

class Review(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name='Товар')
    user_name = models.CharField(default='anonim', max_length=MAX_LENGTH_CHAR, verbose_name='Никнейм пользователя')
    rating = models.PositiveIntegerField(verbose_name='Оценка')
    comment = models.TextField(null=True, blank=True, verbose_name='Комментарий')
    photo = models.ImageField(upload_to='image/review/%Y/%m/%d', null=True, blank=True, verbose_name='Фото в отзыве')

    def __str__(self):
        return f'{self.user_name} - {self.product.name} ({self.rating})'

    class Meta:
        verbose_name = 'Отзыв'
        verbose_name_plural = 'Отзывы'

shop/forms.py
import re
from django.core.exceptions import ValidationError
from django import forms
from .models import *

class ProductFilterForm(forms.Form):
    name = forms.CharField(
        label='Название товара',
        required=False,
        min_length=2,
        max_length=150,
        strip=True,
        widget=forms.TextInput(
            attrs={'class': 'form-control'}
        )
    )
    min_price = forms.DecimalField(
        label='Минимальная цена',
        required=False,
        min_value=0,
        max_digits=10,
        decimal_places=2,
        step_size=0.01,
        widget=forms.NumberInput(
            attrs={'class': 'form-control'}
        )
    )
    max_price = forms.DecimalField(
        label='Максимальная цена',
        required=False,
        min_value=1,
        max_digits=10,
        decimal_places=2,
        step_size=0.01,
        widget=forms.NumberInput(
            attrs={'class': 'form-control'}
        )
    )

shop/views.py
from django.shortcuts import render, get_object_or_404, redirect

from .forms import ProductFilterForm
from .models import *

from django.views.generic import ListView
# Create your views here.

def list_product(request):
    list_product = Product.objects.all()
    context = {
        'list_product': list_product
    }
    return render(request, 'shop/product/all_product.html', context)

def product_list_with_filter(request):
    list_product = Product.objects.all()
    if request.GET != None:
        product_form = ProductFilterForm(request.GET)
    else:
        product_form = ProductFilterForm()

    if product_form.is_valid():
        if product_form.cleaned_data.get('name') != "":
            list_product = list_product.filter(name__icontains=product_form.cleaned_data.get('name'))
        if product_form.cleaned_data.get('min_price'):
            list_product = list_product.filter(price__gte=product_form.cleaned_data.get('min_price'))
        if product_form.cleaned_data.get('max_price'):
            list_product = list_product.filter(price__lte=product_form.cleaned_data.get('max_price'))
        context = {
            'list_product': list_product,
            'form': product_form,
        }
        return render(request, 'shop/product/all_filter_product.html', context)



def get_one_product(request, id):
    product = get_object_or_404(Product, pk=id)
    context = {
        'product': product
    }
    return render(request, 'shop/product/one_product_table.html', context)

def get_one_filter(request):
    find_product = Product.objects.filter(is_exists=request.GET.get('is_ex'))
    context = {
        'list_product': find_product
    }
    return render(request, 'shop/product/all_product.html', context)

def get_more_filter(request):
    find_product = Product.objects.filter(
        price__lte=request.GET.get('max_price'),
        price__gt=request.GET.get('min_price')
    )
    context = {
        'list_product': find_product
    }
    return render(request, 'shop/product/all_product.html', context)

class ListSupplier(ListView):
    model = Supplier
    template_name = 'shop/supplier/supplier_list.html'
    allow_empty = True

shop/templates/shop/product/all_filter_product.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Товары с фильтром</title>
    <link rel="stylesheet" href="{% static 'shop/css/bootstrap.css' %}">
    <style>
        .card-img-top {
            width: 100%;
            height: 25vw;
            object-fit: cover;
        }
    </style>
</head>
<body>
    <div class="container">
    <div class="container">
        <div class="row">
            <div class="col-8">
                <ul>
                    {% if request.user.is_anonymous %}
                        <li><a class="btn btn-outline-primary" href="{% url 'log in' %}">Авторизация</a></li>
                        <li><a class="btn btn-outline-success" href="{% url 'regis' %}">Регистрация</a></li>
                    {% else %}
                        <li><a class="btn btn-outline-danger" href="{% url 'log out' %}">Выход из аккаунта</a></li>
                    {% endif %}
                </ul>
            </div>
            <div class="col-4">
                Здравствуйте, {{ user }}
            </div>
        </div>
    </div>
    <form>
        {{ form.as_div }}
        <button style="margin-top: 20px;" type="submit" class="btn btn-outline-info">Применить фильтр</button>
    </form>
    <h1 style="display: flex; justify-content: center; color: cornflowerblue;">Каталог платьев</h1>
    <div class="container">
        <div class="row">
            {% for product in list_product %}
            <div class="col-4">
                <div class="card" style="width: 18rem;">
                    {% if product.photo %}
                        <img src="{{ product.photo.url }}" class="card-img-top" alt="...">
                    {% else %}
                        <img src="{% static 'shop/image/no_photo.jpg'%}" class="card-img-top" alt="...">
                    {% endif %}
                    <div class="card-body">
                        <h5 class="card-title">{{ product.name }}</h5>
                        <h6 class="card-subtitle mb-2 text-body-secondary">
                            Категория: {{ product.category.name }}
                        </h6>
                        <p class="card-text">{{ product.description }}</p>
                        <p>Цена: {{ product.price }} руб.</p>
                        <p>Дата создания: {{ product.create_date }}</p>
                        {% if request.user.is_authenticated %}
                            <a href="{% url 'get_one_product' product.pk %}" class="btn btn-outline-info">Подробнее...</a>
                        {% endif %}
                    </div>
                </div>
            </div>
        {% endfor %}
        </div>
    </div>
</div>
</body>
</html>

shop/templates/shop/product/all_product.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Все товары</title>
    <link rel="stylesheet" href="{% static 'shop/css/bootstrap.css' %}">
</head>
<body>
<table class="table">
    <tbody class="table-primary">
    {% for product in list_product %}
        <tr>
            <td>
                <div class="row">
                    <div class="col col-3">
                        {{ product.name }} - {{ product.price }}
                    </div>
                    <div class="col col-3">
                        {{ product.description }}
                    </div>
                    <div class="col col-6">
                        Заказы:
                        {% for ord in product.pos_order_set.all %}
                            <ul>
                                <li>
                                    #{{ ord.order.pk }} {{ ord.order.date_create }} - {{ ord.order.buyer_lastname }}
                                    ({{ ord.count }} шт.)
                                </li>
                            </ul>
                        {% empty %}
                            <p>
                                Никто еще не совершил заказы
                            </p>
                        {% endfor %}
                    </div>
                </div>
            </td>
        </tr>
    {% endfor %}
    </tbody>
</table>
</body>
</html>

shop/templates/shop/product/catalog.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Список товаров</title>
</head>
<body>

    {% for product in product_list %}
        <h1>Название продукта: {{ product.name }}</h1>
            <p>{{ product.description }}</p>
    {% endfor %}


</body>
</html>

shop/templates/shop/product/catalog_filter.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Фильтр на товары</title>
    <link rel="stylesheet" href="{% static 'shop/css/bootstrap.css' %}">
    <style>
        .card-img-top {
            width: 100%;
            height: 25vw;
            object-fit: cover;
        }
    </style>
</head>
<body>
    <div class="container">
        <div class="container">
            <div class="row">
                <div class="col-8">
                    <ul>
                        {% if request.user.is_anonymous %}
                            <li><a class="btn btn-outline-primary" href="{% url 'log in' %}">Авторизация</a></li>
                            <li><a style="margin-top: 20px;" class="btn btn-outline-info" href="{% url 'regis' %}">Регистрация</a></li>
                        {% else %}
                            <li><a class="btn btn-outline-danger" href="{% url 'log out' %}">Выход из профиля</a></li>
                        {% endif %}
                    </ul>
                </div>
                <div class="col-4">
                    Здравствуйте, {{ user }}
                </div>
            </div>
        </div>

        <form>
            {{ form.as_div }}
            <button style="margin-top: 20px;" type="submit" class="btn btn-info">Применить фильтр</button>
        </form>
        <h1 style="display: flex; justify-content: center; color: #6f42c1">Каталог платьев</h1>
        <div class="container">
            <div class="row">
                {% for product in list_product %}
                    <div class="col-4">
                        <div class="card" style="width: 18rem;">
                            {% if product.photo %}
                                <img src="{{ product.photo.url }}" class="card-img-top" alt="...">
                            {% else %}
                                <img src="{% static 'shop/image/no_photo.jpg'%}" class="card-img-top" alt="...">
                            {% endif %}
                        <div class="card-body">
                            <h5 class="card-title">{{ product.name }}</h5>
                            <h6 class="card-subtitle mb-2 text-body-secondary">
                                Категория: {{ product.category.name }}
                            </h6>
                            <p class="card-text">
                                {{ product.description }}
                            </p>
                            <p class="card-text">
                                Цена: {{ product.price }} руб.
                            </p>
                            {% if request.user.is_authenticated %}
                                <a href="{% url 'get_one_product' product.pk %}" class="btn btn-outline-info">Подробнее ...</a>
                            {% endif %}
                        </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>


    </div>
</body>
</html>

shop/templates/shop/product/one_product.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Информация о {{ product.name }}</title>
    <link rel="stylesheet" href="{% static 'shop/css/bootstrap.css' %}">
</head>
<body>
    <h1 style="justify-content: center; display: flex; color: #ffda38">{{ product.name }}</h1>
    __________________________________
    <p>{{ product.description }}</p>
    <p>{{ product.price }} руб.</p>
    <p>{{ product.create_date }}</p>
    <div style="display: flex; justify-content: center;">
    {% if product.photo %}
        <img src="{{ product.photo.url }}" class="card-img-top" alt="..." style="max-height: 400px; max-width: 400px;">
    {% else %}
        <img src="{% static 'shop/image/no_photo.jpg'%}" class="card-img-top" alt="..." style="max-height: 400px; max-width: 400px;">
    {% endif %}
    </div>
</body>
</html>

shop/templates/shop/product/one_product_table.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="{% static 'shop/css/bootstrap.css' %}">
</head>
<body>
<h1 style="display: flex; justify-content: center; color: sandybrown">Подробнее о {{ product.name }}</h1>
<div class="p-3">
    <table class="table table-bordered table-dark">
        <thead class="table-primary">
        <tr>
            <th>Название</th>
            <th>Описание</th>
            <th>Стоимость</th>
            <th>В наличии на складе</th>
            <th>Теги</th>
            <th>Картинка</th>
        </tr>
        </thead>
        <tbody>
        <tr>
            <td>{{ product.name }}</td>
            <td>
                {% if product.description %}
                    {{ product.description }}
                {% else %}
                    Описание отсутствует
                {% endif %}
            </td>
            <td>{{ product.price }}</td>
            <td>
                <ul>
                    {% for warehouse in product.warehouse.all %}
                        <li>{{ warehouse.location }}</li>
                    {% empty %}
                        <li>Нет в наличии на складах</li>
                    {% endfor %}
                </ul>
            </td>
            <td>
                <ul>
                    {% for tag in product.tag.all %}
                        <li>{{ tag.name }}</li>
                    {% empty %}
                        <li>Нет актуальных тегов</li>
                    {% endfor %}
                </ul>
            </td>
            <td>
                {% if product.photo %}
                    <img src="{{ product.photo.url }}" alt="..." style="max-width: 400px; max-height: 400px; object-fit: contain; border-radius: 50%">
                {% else %}
                    <img src="{% static 'shop/image/no_photo.jpg' %}" alt="..." style="max-width: 400px; max-height: 400px; object-fit: contain;">
                {% endif %}
            </td>
        </tr>
        </tbody>
    </table>
    <a href="{% url 'product_list_filter' %}" class="btn btn-outline-dark" >Назад к каталогу</a>
</div>
</body>
</html>

shop/templates/shop/product/query_filter_product.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Список товаров</title>
</head>
<body>
    {% for product in find_product %}
        <h1>Название продукта: {{ product.name }}</h1>
            <p>{{ product.description }}</p>
    {% endfor %}


</body>
</html>